### ISSUE TITLE
waveset reader: close file at the end

### ISSUE THREAD

**Issue by JonasReubelt** [JonasReubelt/PeeEmTee.jl#2]

**Comment by tamasgal** [comment]
I think it's closed afterwards `;)`

https://github.com/JonasReubelt/PeeEmTee.jl/blob/898ea0816dfc37e0c88d03d5521de75a9d60aaa2/src/tools.jl#L10

But maybe a `do-block` would be better in case something happens between `h5open` and `close`, this would leave the file in an open state.

**Comment by tamasgal** [comment]
Ah ok, this is the wrong repository ;)
